ALTER TABLE cards
ADD COLUMN IF NOT EXISTS public_id VARCHAR(36) UNIQUE,
ADD COLUMN IF NOT EXISTS last4 VARCHAR(4),
ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, BLOCKED, EXPIRED
ADD COLUMN IF NOT EXISTS holder_name VARCHAR(80),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
ADD COLUMN IF NOT EXISTS is_primary BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS cvv VARCHAR(4);

CREATE INDEX IF NOT EXISTS idx_cards_account ON cards(account_id);
CREATE INDEX IF NOT EXISTS idx_card_public_id ON cards(public_id);